"""initial ontology schema

Revision ID: 8aa1b5cadfc9
Revises: 
Create Date: 2026-09-25 08:32:15.837638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aa1b5cadfc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('object_literal', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('verification_state', sa.String(length=32), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_object_id'), 'claim', ['object_id'], unique=False)
    op.create_index(op.f('ix_claim_predicate'), 'claim', ['predicate'], unique=False)
    op.create_index(op.f('ix_claim_subject_id'), 'claim', ['subject_id'], unique=False)
    op.create_index(op.f('ix_claim_subject_type'), 'claim', ['subject_type'], unique=False)
    op.create_table('interaction',
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_subject_id'), 'interaction', ['subject_id'], unique=False)
    op.create_table('merge_log',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('surviving_id', sa.UUID(), nullable=False),
    sa.Column('merged_id', sa.UUID(), nullable=False),
    sa.Column('merge_reason', sa.Text(), nullable=True),
    sa.Column('match_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('merged_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merge_log_merged_id'), 'merge_log', ['merged_id'], unique=False)
    op.create_index(op.f('ix_merge_log_surviving_id'), 'merge_log', ['surviving_id'], unique=False)
    op.create_table('organisation',
    sa.Column('legal_name', sa.String(length=512), nullable=False),
    sa.Column('trading_names', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('org_type', sa.String(length=32), nullable=False),
    sa.Column('legal_form', sa.String(length=128), nullable=True),
    sa.Column('company_number', sa.String(length=64), nullable=True),
    sa.Column('lei', sa.String(length=20), nullable=True),
    sa.Column('vat_id', sa.String(length=32), nullable=True),
    sa.Column('jurisdiction', sa.String(length=2), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('hq_country', sa.String(length=2), nullable=True),
    sa.Column('hq_city', sa.String(length=255), nullable=True),
    sa.Column('revenue_eur_estimate', sa.Integer(), nullable=True),
    sa.Column('employee_estimate', sa.Integer(), nullable=True),
    sa.Column('ownership_class', sa.String(length=32), nullable=False),
    sa.Column('direct_parent_id', sa.UUID(), nullable=True),
    sa.Column('ultimate_parent_id', sa.UUID(), nullable=True),
    sa.Column('data_completeness_score', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['direct_parent_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['ultimate_parent_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisation_company_number'), 'organisation', ['company_number'], unique=False)
    op.create_index(op.f('ix_organisation_domain'), 'organisation', ['domain'], unique=False)
    op.create_index(op.f('ix_organisation_legal_name'), 'organisation', ['legal_name'], unique=False)
    op.create_index(op.f('ix_organisation_lei'), 'organisation', ['lei'], unique=True)
    op.create_table('source_registry',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('root_domain', sa.String(length=255), nullable=True),
    sa.Column('data_categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('geography', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('access_method', sa.String(length=128), nullable=True),
    sa.Column('update_cadence', sa.String(length=64), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('required_credential_env', sa.String(length=128), nullable=True),
    sa.Column('licence_status', sa.String(length=32), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('licence_notes', sa.Text(), nullable=True),
    sa.Column('licence_reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('licence_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rate_limit_notes', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_successful_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('reliability_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('watchlist',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure_cluster',
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('authority_org_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=16), nullable=True),
    sa.Column('municipality', sa.String(length=255), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geometry_precision', sa.String(length=32), nullable=False),
    sa.Column('sensitivity_level', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['authority_org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_cluster_country'), 'infrastructure_cluster', ['country'], unique=False)
    op.create_table('infrastructure_network',
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('operator_org_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=16), nullable=True),
    sa.Column('municipality', sa.String(length=255), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geometry_precision', sa.String(length=32), nullable=False),
    sa.Column('sensitivity_level', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['operator_org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_network_country'), 'infrastructure_network', ['country'], unique=False)
    op.create_table('ingestion_run',
    sa.Column('source_registry_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_registry_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_run_source_registry_id'), 'ingestion_run', ['source_registry_id'], unique=False)
    op.create_table('public_authority_detail',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('authority_level', sa.String(length=64), nullable=True),
    sa.Column('regulatory_scope', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id')
    )
    op.create_table('role',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('role_category', sa.String(length=64), nullable=False),
    sa.Column('title_as_seen', sa.String(length=255), nullable=True),
    sa.Column('is_filled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_organisation_id'), 'role', ['organisation_id'], unique=False)
    op.create_table('source',
    sa.Column('source_registry_id', sa.UUID(), nullable=True),
    sa.Column('publisher', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_excerpt', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_registry_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_item',
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('item_value', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_item_watchlist_id'), 'watchlist_item', ['watchlist_id'], unique=False)
    op.create_table('evidence',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    op.create_table('infrastructure_asset',
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('alt_names', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('operational_description', sa.Text(), nullable=True),
    sa.Column('capacity_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('importance_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('operator_org_id', sa.UUID(), nullable=True),
    sa.Column('owner_org_id', sa.UUID(), nullable=True),
    sa.Column('ultimate_owner_org_id', sa.UUID(), nullable=True),
    sa.Column('public_authority_org_id', sa.UUID(), nullable=True),
    sa.Column('network_id', sa.UUID(), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('osm_id', sa.String(length=64), nullable=True),
    sa.Column('facility_code', sa.String(length=128), nullable=True),
    sa.Column('source_confidence', sa.Integer(), nullable=True),
    sa.Column('data_completeness_score', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', sa.Date(), nullable=True),
    sa.Column('last_updated_at', sa.Date(), nullable=True),
    sa.Column('sales_readiness_state', sa.String(length=32), nullable=False),
    sa.Column('strategic_importance', sa.Integer(), nullable=True),
    sa.Column('physical_complexity', sa.Integer(), nullable=True),
    sa.Column('response_complexity', sa.Integer(), nullable=True),
    sa.Column('autonomous_fit', sa.Integer(), nullable=True),
    sa.Column('security_intensity', sa.Integer(), nullable=True),
    sa.Column('buyer_accessibility', sa.Integer(), nullable=True),
    sa.Column('contactability', sa.Integer(), nullable=True),
    sa.Column('procurement_signal', sa.Integer(), nullable=True),
    sa.Column('change_signal', sa.Integer(), nullable=True),
    sa.Column('data_confidence', sa.Integer(), nullable=True),
    sa.Column('lares_fit', sa.Integer(), nullable=True),
    sa.Column('status_pipeline_stage', sa.String(length=32), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=16), nullable=True),
    sa.Column('municipality', sa.String(length=255), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geometry_precision', sa.String(length=32), nullable=False),
    sa.Column('sensitivity_level', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['infrastructure_cluster.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['infrastructure_network.id'], ),
    sa.ForeignKeyConstraint(['operator_org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['owner_org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['public_authority_org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['ultimate_owner_org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_asset_canonical_name'), 'infrastructure_asset', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_category'), 'infrastructure_asset', ['category'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_cluster_id'), 'infrastructure_asset', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_country'), 'infrastructure_asset', ['country'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_lares_fit'), 'infrastructure_asset', ['lares_fit'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_network_id'), 'infrastructure_asset', ['network_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_operator_org_id'), 'infrastructure_asset', ['operator_org_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_osm_id'), 'infrastructure_asset', ['osm_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_owner_org_id'), 'infrastructure_asset', ['owner_org_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_public_authority_org_id'), 'infrastructure_asset', ['public_authority_org_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_sales_readiness_state'), 'infrastructure_asset', ['sales_readiness_state'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_subcategory'), 'infrastructure_asset', ['subcategory'], unique=False)
    op.create_index(op.f('ix_infrastructure_asset_ultimate_owner_org_id'), 'infrastructure_asset', ['ultimate_owner_org_id'], unique=False)
    op.create_table('person',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('public_role_title', sa.String(length=255), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('role_category', sa.String(length=64), nullable=True),
    sa.Column('public_profile_url', sa.Text(), nullable=True),
    sa.Column('public_corporate_contact', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_organisation_id'), 'person', ['organisation_id'], unique=False)
    op.create_table('physical_site',
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('operator_org_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=16), nullable=True),
    sa.Column('municipality', sa.String(length=255), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geometry_precision', sa.String(length=32), nullable=False),
    sa.Column('sensitivity_level', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['infrastructure_cluster.id'], ),
    sa.ForeignKeyConstraint(['operator_org_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_site_cluster_id'), 'physical_site', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_physical_site_country'), 'physical_site', ['country'], unique=False)
    op.create_table('relationship',
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('verification_state', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_object_id'), 'relationship', ['object_id'], unique=False)
    op.create_index(op.f('ix_relationship_object_type'), 'relationship', ['object_type'], unique=False)
    op.create_index(op.f('ix_relationship_predicate'), 'relationship', ['predicate'], unique=False)
    op.create_index(op.f('ix_relationship_subject_id'), 'relationship', ['subject_id'], unique=False)
    op.create_index(op.f('ix_relationship_subject_type'), 'relationship', ['subject_type'], unique=False)
    op.create_table('procurement_notice',
    sa.Column('ted_notice_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('contracting_authority_org_id', sa.UUID(), nullable=True),
    sa.Column('infrastructure_asset_id', sa.UUID(), nullable=True),
    sa.Column('cpv_codes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('security_relevance_category', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('value_eur_estimate', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('deadline_at', sa.Date(), nullable=True),
    sa.Column('contract_duration_months', sa.Integer(), nullable=True),
    sa.Column('awarded_to_org_id', sa.UUID(), nullable=True),
    sa.Column('award_value_eur', sa.Integer(), nullable=True),
    sa.Column('possible_renewal_date', sa.Date(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['awarded_to_org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['contracting_authority_org_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['infrastructure_asset_id'], ['infrastructure_asset.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_notice_contracting_authority_org_id'), 'procurement_notice', ['contracting_authority_org_id'], unique=False)
    op.create_index(op.f('ix_procurement_notice_infrastructure_asset_id'), 'procurement_notice', ['infrastructure_asset_id'], unique=False)
    op.create_index(op.f('ix_procurement_notice_ted_notice_id'), 'procurement_notice', ['ted_notice_id'], unique=True)
    op.create_table('project',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('infrastructure_asset_id', sa.UUID(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('capex_eur_estimate', sa.Integer(), nullable=True),
    sa.Column('funding_source', sa.String(length=255), nullable=True),
    sa.Column('announced_at', sa.Date(), nullable=True),
    sa.Column('expected_completion', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_asset_id'], ['infrastructure_asset.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_infrastructure_asset_id'), 'project', ['infrastructure_asset_id'], unique=False)
    op.create_index(op.f('ix_project_organisation_id'), 'project', ['organisation_id'], unique=False)
    op.create_table('signal',
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('detected_at', sa.Date(), nullable=True),
    sa.Column('infrastructure_asset_id', sa.UUID(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('commercial_relevance_note', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('verification_state', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('half_life_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_asset_id'], ['infrastructure_asset.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_infrastructure_asset_id'), 'signal', ['infrastructure_asset_id'], unique=False)
    op.create_index(op.f('ix_signal_organisation_id'), 'signal', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_signal_signal_type'), 'signal', ['signal_type'], unique=False)
    # NOTE: 'spatial_ref_sys' is a PostGIS system table; intentionally not dropped.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_signal_type'), table_name='signal')
    op.drop_index(op.f('ix_signal_organisation_id'), table_name='signal')
    op.drop_index(op.f('ix_signal_infrastructure_asset_id'), table_name='signal')
    op.drop_table('signal')
    op.drop_index(op.f('ix_project_organisation_id'), table_name='project')
    op.drop_index(op.f('ix_project_infrastructure_asset_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_procurement_notice_ted_notice_id'), table_name='procurement_notice')
    op.drop_index(op.f('ix_procurement_notice_infrastructure_asset_id'), table_name='procurement_notice')
    op.drop_index(op.f('ix_procurement_notice_contracting_authority_org_id'), table_name='procurement_notice')
    op.drop_table('procurement_notice')
    op.drop_index(op.f('ix_relationship_subject_type'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_subject_id'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_predicate'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_object_type'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_object_id'), table_name='relationship')
    op.drop_table('relationship')
    op.drop_index(op.f('ix_physical_site_country'), table_name='physical_site')
    op.drop_index(op.f('ix_physical_site_cluster_id'), table_name='physical_site')
    op.drop_table('physical_site')
    op.drop_index(op.f('ix_person_organisation_id'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_infrastructure_asset_ultimate_owner_org_id'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_subcategory'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_sales_readiness_state'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_public_authority_org_id'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_owner_org_id'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_osm_id'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_operator_org_id'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_network_id'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_lares_fit'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_country'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_cluster_id'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_category'), table_name='infrastructure_asset')
    op.drop_index(op.f('ix_infrastructure_asset_canonical_name'), table_name='infrastructure_asset')
    op.drop_table('infrastructure_asset')
    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_watchlist_item_watchlist_id'), table_name='watchlist_item')
    op.drop_table('watchlist_item')
    op.drop_table('source')
    op.drop_index(op.f('ix_role_organisation_id'), table_name='role')
    op.drop_table('role')
    op.drop_table('public_authority_detail')
    op.drop_index(op.f('ix_ingestion_run_source_registry_id'), table_name='ingestion_run')
    op.drop_table('ingestion_run')
    op.drop_index(op.f('ix_infrastructure_network_country'), table_name='infrastructure_network')
    op.drop_table('infrastructure_network')
    op.drop_index(op.f('ix_infrastructure_cluster_country'), table_name='infrastructure_cluster')
    op.drop_table('infrastructure_cluster')
    op.drop_table('watchlist')
    op.drop_table('source_registry')
    op.drop_index(op.f('ix_organisation_lei'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_legal_name'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_domain'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_company_number'), table_name='organisation')
    op.drop_table('organisation')
    op.drop_index(op.f('ix_merge_log_surviving_id'), table_name='merge_log')
    op.drop_index(op.f('ix_merge_log_merged_id'), table_name='merge_log')
    op.drop_table('merge_log')
    op.drop_index(op.f('ix_interaction_subject_id'), table_name='interaction')
    op.drop_table('interaction')
    op.drop_index(op.f('ix_claim_subject_type'), table_name='claim')
    op.drop_index(op.f('ix_claim_subject_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_predicate'), table_name='claim')
    op.drop_index(op.f('ix_claim_object_id'), table_name='claim')
    op.drop_table('claim')
    # ### end Alembic commands ###
