"""review queue

Revision ID: e2798bda4cee
Revises: bf8f0f581ce5
Create Date: 2026-09-25 08:34:04.531013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2798bda4cee'
down_revision: Union[str, None] = 'bf8f0f581ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_queue_item',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('candidate_natural_key', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_entity_id', sa.UUID(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('match_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_item_entity_type'), 'review_queue_item', ['entity_type'], unique=False)
    op.create_index(op.f('ix_review_queue_item_status'), 'review_queue_item', ['status'], unique=False)
    # NOTE: 'spatial_ref_sys' is a PostGIS system table; intentionally not dropped.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_queue_item_status'), table_name='review_queue_item')
    op.drop_index(op.f('ix_review_queue_item_entity_type'), table_name='review_queue_item')
    op.drop_table('review_queue_item')
    # ### end Alembic commands ###
